stages:
  - build
  - test
  - push

variables:
  IMAGE_NAME: exam052026
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_HUB_USER: jordiabata2003-art

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  script:
    - docker build -t $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG .
  only:
    - main

test:
  stage: test
  image: aquasec/trivy:latest
  script:
    - trivy image $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG --exit-code 0 --severity HIGH,CRITICAL
  only:
    - main

push:
  stage: push
  image: docker:20.10.16
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  script:
    - docker push $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG
    - docker tag $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG $DOCKER_HUB_USER/$IMAGE_NAME:latest
    - docker push $DOCKER_HUB_USER/$IMAGE_NAME:latest
  only:
    - main
